openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:

  /v1/api/{companyId}:
    post:
      summary: тестовый summary
      operationId: testApi
      parameters:
        - name: companyId
          in: path
          required: true
          description: Идентификатор компании
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/NwkRawRawValueObjectClass"
      responses:
        '200':
          description: Список категорий продуктов
          content:
            application/json:
              schema:
                type: string
                enum:
                  - success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NwkError"